In [1]:
import numpy as np
arr=np.array([1,2,3])
print(arr)

[1 2 3]


# Exercise 1: NumPy: Create an array with values ranging from 12 to 38

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]

In [2]:
arr=np.array(range(12,38,1))
print(arr)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


# Exercise 2: Add a border around an existing array
Hint: np.pad()
Original array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
0 on the border and 1 inside in the array
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]

In [3]:
x=np.ones((3,3))
print("Original array:")
print(x)
print("0 on the border and 1 inside in the array")
y=np.pad(x,pad_width=1,mode='constant',constant_values=0)
print(y)

Original array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
0 on the border and 1 inside in the array
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


# Exercise 3: Convert a list and tuple into arrays
List to array: 
[1 2 3 4 5 6 7 8]
Tuple to array: 
[[8 4 6]
 [1 2 3]]
Also try np.asarray for the problem above!

In [4]:
l1 =[1,2,3,4,5,6,7,8]
#print(type(l1))
print("List is", l1)
l2=np.asarray(l1)
#print(type(l2))
print("List to array is", l2)
t1=((8,4,6),(1,2,3))
#print(type(t1))
print("Tuple is", t1)
t2=np.asarray(t1)
#print(type(t2))
print("Tuple to array is")
print(t2)

List is [1, 2, 3, 4, 5, 6, 7, 8]
List to array is [1 2 3 4 5 6 7 8]
Tuple is ((8, 4, 6), (1, 2, 3))
Tuple to array is
[[8 4 6]
 [1 2 3]]


# Exercise 4: Convert the values of Centigrade degrees into Fahrenheit degrees

Values in Fahrenheit degrees:
[ 0.   12.   45.21 34.   99.91]
Values in  Centigrade degrees:
[-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]

In [5]:
Farenheit=np.array([0,12,45.21,34,99.91])
print("Values in Farenheit Degrees\n",Farenheit)
Centigrade=(Farenheit - 32)*5/9
print("Values in Centigrade Degrees\n",Centigrade)

Values in Farenheit Degrees
 [ 0.   12.   45.21 34.   99.91]
Values in Centigrade Degrees
 [-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


# Exercise 5: Write a NumPy program to find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements.

Size of the array:  3
Length of one array element in bytes:  8
Total bytes consumed by the elements of the array:  24

In [6]:
arr=np.array([1,2,3,4,5])
s=arr.size
#s=len(arr)
print("Size of the array:\n",s)
print("Length of one array element in bytes:\n",arr.itemsize)
i=arr.itemsize
ans=s*i
print("Total bytes consumed by the elements of the array:\n",ans)

Size of the array:
 5
Length of one array element in bytes:
 4
Total bytes consumed by the elements of the array:
 20


# Exercise 6: Get the unique elements of an array

Original array:
[10 10 20 20 30 30]
Unique elements of the above array:
[10 20 30]
Original array:
[[1 1]
 [2 3]]
Unique elements of the above array:
[1 2 3]

In [7]:
arr1=np.array([10,10,20,20,30,30])
print("Original array:\n",arr1)
arr2=np.unique(arr1)
print("Unique elements of the above array:\n",arr2)
arr3=np.array(([1,1],[2,3]))
print("Original array:\n",arr3)
arr4=np.unique(arr3)
print("Unique elements of the above array:\n",arr4)

Original array:
 [10 10 20 20 30 30]
Unique elements of the above array:
 [10 20 30]
Original array:
 [[1 1]
 [2 3]]
Unique elements of the above array:
 [1 2 3]


# Exercise 7: Change the dimension of an array

Original array: [1 2 3 4 5 6 7 8 9]
Change array shape to (3, 3) -> 3 rows and 3 columns 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

In [8]:
arr1=np.array([1,2,3,4,5,6,7,8,9])
print("Original array:\n",arr)
arr2=arr1.reshape(3,3)
print("Reshaped array:\n",arr2)

Original array:
 [1 2 3 4 5]
Reshaped array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


# Exercise 8: Create a 1-D array of 30 evenly spaced elements between 2.5. and 6.5, inclusive

[2.5        2.63793103 2.77586207 2.9137931  3.05172414 3.18965517
 3.32758621 3.46551724 3.60344828 3.74137931 3.87931034 4.01724138
 4.15517241 4.29310345 4.43103448 4.56896552 4.70689655 4.84482759
 4.98275862 5.12068966 5.25862069 5.39655172 5.53448276 5.67241379
 5.81034483 5.94827586 6.0862069  6.22413793 6.36206897 6.5       ]

In [9]:
arr=np.linspace(2.5,6.5,30)
print("Elements are:\n",arr)

Elements are:
 [2.5        2.63793103 2.77586207 2.9137931  3.05172414 3.18965517
 3.32758621 3.46551724 3.60344828 3.74137931 3.87931034 4.01724138
 4.15517241 4.29310345 4.43103448 4.56896552 4.70689655 4.84482759
 4.98275862 5.12068966 5.25862069 5.39655172 5.53448276 5.67241379
 5.81034483 5.94827586 6.0862069  6.22413793 6.36206897 6.5       ]


# Convert 1-D arrays as columns into a 2-D array

Array1: [10 20 30]
Array2: [40 50 60]
Converted array
[[10 40]
 [20 50]
 [30 60]]

In [10]:
arr1=np.array(([10,20,30],[40,50,60]))
print("Original array is\n", arr1)
arr2=arr1.transpose()
print(arr2)
#s=np.shape(arr2)
#print(s)


Original array is
 [[10 20 30]
 [40 50 60]]
[[10 40]
 [20 50]
 [30 60]]


# Exercise 10: Create a 5x5 matrix with row values ranging from 0 to 4

Original array:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Row values ranging from 0 to 4.
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]