# Exercise 10: Create a 5x5 matrix with row values ranging from 0 to 4
*******************************DOUBT******************************
Original array:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Row values ranging from 0 to 4.
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]

In [1]:
import numpy as np
arr1=np.zeros((5,5))
print(arr1)
arr2+=np.arange(5)
print(arr2)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


NameError: name 'arr2' is not defined

# Exercise 11: Sum of all the multiples of 3 or 5 below 100
[ 3  5  6  9 10 12 15 18 20 21 24 25 27 30 33 35 36 39 40 42 45 48 50 51
 54 55 57 60 63 65 66 69 70 72 75 78 80 81 84 85 87 90 93 95 96 99]
2318

In [ ]:
sum=0
l1=[]
arr1=np.arange(1,100,1)
#print(arr1)
for i in arr1:
    if((i%3==0) or (i%5==0)):
        l1.append(i)
        sum=sum+i
print("The numbers are\n",l1)
print("The ans is:\n",sum)
        

# Exercise 12: Combine a one and a two dimensional array together and display their elements
************doubt******************
Hint : np.nditer()
x = np.arange(4)
y = np.arange(4)
for a, b in np.nditer([x,y]):
    print(a)
    print(b)
0
0
1
1
2
2
3
3
:::::::
One dimensional array:
[0 1 2 3]
Two dimensional array:
[[0 1 2 3]
 [4 5 6 7]]
0:0
1:1
2:2
3:3
0:4
1:5
2:6
3:7

# Exercise 13: Write a NumPy program to replace all elements of NumPy array that are greater than specified array.

Original array:
[[0.42436315 0.48558583 0.32924763]
 [0.7439979  0.58220701 0.38213418]
 [0.5097581  0.34528799 0.1563123 ]]
Replace all elements of the said array with .5 which are greater than .5
[[0.42436315 0.48558583 0.32924763]
 [0.5        0.5        0.38213418]
 [0.5        0.34528799 0.1563123 ]]

In [3]:
arr1=np.array([[0.42436315, 0.48558583, 0.32924763],[0.7439979, 0.58220701, 0.38213418],[0.5097581,0.34528799,0.1563123]])
print("Original array:\n\n",arr1)
#print(arr1)
search=float(input("\nEnter the element to search:\n"))
replace=float(input("Enter the element to replace:\n"))
arr1[arr1==search]=replace
print("\nReplaced final array\n\n",arr1)

Original array:

 [[0.42436315 0.48558583 0.32924763]
 [0.7439979  0.58220701 0.38213418]
 [0.5097581  0.34528799 0.1563123 ]]

Enter the element to search:
0.1563123
Enter the element to replace:
99.000

Replaced final array

 [[ 0.42436315  0.48558583  0.32924763]
 [ 0.7439979   0.58220701  0.38213418]
 [ 0.5097581   0.34528799 99.        ]]


# Exercise 14: Add a new row to an empty numpy array

Empty array:
[]
After adding two new arrays:
[[10 20 30]
 [40 50 60]]

In [21]:
l1=[]
arr1=np.array(l1)
print("Empty array:\n",arr1)
arr1=np.append(arr1,[10,20,30])
print("After adding two new arrays:\n",arr2)

Empty array:
 []
After adding two new arrays:
 [10. 20. 30.]
